sudo: required
install: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

stages:
  - test
  - name: deploy
    if: branch = master
  - name: docs
    if: branch = master

jobs:
  include:
    - stage: test
      before_script:
        - env | grep 'TWITTER' > secrets
        - nanobox evar load local secrets
        - rm secrets
      script: nanobox run mix test
    - stage: deploy
      script: skip
      after_success:
        - nanobox remote add memento
        - nanobox deploy
    - stage: docs
      before_script:
        - env | grep 'SURGE' > secrets
        - nanobox evar load local secrets
        - rm secrets
      script:
        - nanobox run mix docs
        - nanobox run npm install -g surge
        - nanobox run surge -d memento-docs.surge.sh -p doc
